name: Mirror to Personal Repository

on:
  push:
    # Este workflow se ejecutará en cada push a cualquier rama.

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para traer todo el historial de commits
          
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TARGET_REPO_SSH_KEY }}
          
      - name: Push to target repository
        run: |
          # Añadir la huella del servidor de GitHub para evitar prompts
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          # Añadir el remoto destino (el personal de diego-martucho)
          git remote add target git@github.com:diego-martucho/mia-altech-frontend.git
          
          # Empujar el ref actual (ya sea rama o tag) al repositorio destino
          git push --force target HEAD:${GITHUB_REF}